# permissions for end users to view stunnergateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: stunnergateway-viewer-role
rules:
- apiGroups:
  - ingress.nebula.io
  resources:
  - stunnergateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.nebula.io
  resources:
  - stunnergateways/status
  verbs:
  - get
