# permissions for end users to edit stunneringresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: stunneringress-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - stunneringresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - stunneringresses/status
  verbs:
  - get
